# Workflow name
name: PR Preview - Storybook

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]  # Triggers on PR creation, updates, and closure
    branches:
      - main # Change to your default branch

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write  # Needed to comment on the PR

jobs:
  deploy:
    if: github.event.action != 'closed'  # Run only if PR is NOT closed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci --prefix frontend

      - name: Build Storybook
        run: npm run build-storybook --prefix frontend

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.event.pull_request.number }} # Ensure unique artifact name
          path: frontend/storybook-static

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.event.pull_request.number }} # Match the unique artifact name

      - name: Comment Storybook Preview Link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook-preview
          message: |
            🚀 Storybook preview is ready!  
            🔗 [View Storybook Preview](https://your-user.github.io/your-repo/pr-${{ github.event.pull_request.number }})

  cleanup:
    if: github.event.action == 'closed'  # Run only if PR is closed (merged or manually closed)
    runs-on: ubuntu-latest
    steps:
      - name: Remove Storybook Preview
        run: gh run cancel ${{ github.run_id }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: storybook-preview
          delete: true
